[package]
name = "leptos_altview"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
quote = "1.0"

[lib]
proc-macro = true

[workspace]
members = [
  ".",
  "leptos_altview_test"
]